### ISSUE TITLE
Minimum compatibility is ESP-IDF v4.2?

### ISSUE THREAD

**Issue by tobymurray** [BrianPugh/cookiecutter-esp32-webserver#2]
So far as I'm aware, the most recent stable release of the ESP-IDF is v4.0.1. That version does not have `esp_system`, nor `esp_netif`, nor ESP32-S2 support.

Taking a quick look at the content of this repo, it appears it relies on versions >= 4.2 or on the head of `master`. Both of these are not "released" versions and can have significant bugs. Potentially worthwhile calling out the ESP-IDF compatibility of this cookiecutter? I mention this because I use v4.0.1 and was pumped to see this project, only to realize it doesn't build against the latest stable release.

**Comment by BrianPugh** [comment]
hey @tobymurray ! I'll make it compatible with v4.0.1 right now.

**Comment by BrianPugh** [comment]
hitting some odd build errors; will continue working on this later tonight. It's slightly less trivial than I was hoping.

**Comment by tobymurray** [comment]
Yeah, it seems like there's been some reasonably significant changes in between 4.0.1 and the head of `master`. Part of it is the [TCP/IP adapter migration](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/tcpip_adapter_migration.html) (although un-migrating in this case), which is anything around `esp_netif`.

Maybe it makes sense to version this cookiecutter for the IDF versions? Presuming development continues on the IDF and 4.2 eventually makes its way to stable, it'd be a shame to have to redo the work here.

**Comment by BrianPugh** [comment]
those changes aren't that big of a deal; I'm just having some weird build issues in regard to mbedtls when using cmake. It could be an esp-idf issue; just needs more time.

**Comment by BrianPugh** [comment]
I pushed my current work-in-progress to branch `v4.0.1_compat`. I get a bunch of mbedtls linking errors when trying to build with `4.0.1`, so we have two options at this point:

1. If you can figure out how to solve those linking issues (it might be an esp-idf issue? or it could be an issue with my local installation), then we can proceed with compatibility.
2. If we cannot figure it out, then we can just put a esp-idf compatibility disclaimer in the README as your PR says.

**Comment by tobymurray** [comment]
Either my environment is similarly borked (which is possible, I moved it to the head of `master` to try this project out), or it's not an environmental issue - I get a whole whack load of `undefined reference to `mbedtls_ecp_copy'` and similar.

With nothing jumping out at me locally, I poked through some of the ESP-IDF issues, and it seems like at least one other person is running into something similar: https://github.com/espressif/esp-idf/issues/5641

Refreshingly, it's reproducible with one of the very simple examples. I'm not going to look closer until someone weighs in on the ESP-IDF issue.

**Comment by tobymurray** [comment]
I tried this out on a Windows 10 machine and I don't run into the mbedtls issues. What OS are you using, @BrianPugh? On my Windows 10 machine I have stayed on v4.0.1, I haven't gone to 4.2 or `master`, so might be something not getting cleaned up somewhere (although I'm pretty sure I did a `git clean`).

**Comment by BrianPugh** [comment]
I'm using ubuntu; I'll try messing around more, but i'm pretty sure I tried a "from scratch" 4.0.1 setup.

**Comment by BrianPugh** [comment]
so i did a super clean installation where I:

1. deleted my `esp-idf` folder
2. deleted my `~/.espressif` folder
3. rebooted my computer, because why not.

After this I:

1. directly cloned v4.0.1 of esp-idf `git clone -b v4.0.1 --recursive https://github.com/espressif/esp-idf.git`
2. ran `./install.sh`
3. `source export.sh`
4. navigated to my freshly cloned cookiecutter repo
5. Same mbedtls errors

**Comment by tobymurray** [comment]
In the ticket linked above, the other person running into the same error (minimal change from an example project) is also on Ubuntu. Potentially an OS related regression? I have no explanation, it works on my Windows machine without all the acrobatics, and I tried the same (full clean and "reinstall"), although I didn't reboot my computer.

Frustrating, as this should "just work" I think.

**Comment by tobymurray** [comment]
I circled back to this, 4.1 is stable and the `v4.0.1_compat` branch builds successfully now with 4.1. `master` continues to require >= 4.2

**Comment by BrianPugh** [comment]
nice! so are you fine with me merging `v4.0.1_compat` into master then?

**Comment by tobymurray** [comment]
Yeah - if it works for you. I'm going to play with it this afternoon, so I'll let you know if I run into anything else

**Comment by BrianPugh** [comment]
i'll just change the 4.2.0 references to 4.1.0 and remove my TODOs

**Comment by BrianPugh** [comment]
@tobymurray sorry I'm just really getting back around to this, which tag of esp-idf would you like this to work with?

**Comment by tobymurray** [comment]
I tried with 4.1 and 4.2 (which was released like a week ago?) and the compatibility branch worked with both. I have no real preference between the two, I'll likely be using 4.2 going forwards as it's the latest stable release.

**Comment by BrianPugh** [comment]
I've decided to just keep this a separate branch and to add instructions to the readme; it'll keep the code base a little cleaner for elements of code that probably won't be used in a year or two.
